name: tech_news
description: "Stay updated with the latest tech news using Tech News Hub, built with state-of-the-art Flutter technologies like BLoC, Get-It, and Clean Architecture. Enjoy real-time updates, personalized content, and a user-friendly interface designed to keep you informed about the tech world effortlessly."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.0
  dio: ^5.5.0+1
  pretty_dio_logger: ^1.4.0
  flutter_bloc: ^8.1.1
  bloc_concurrency: ^0.2.1
  flutter_svg: ^1.1.6
  get_it: ^7.2.0
  infinite_scroll_pagination: ^3.2.0
  intl: ^0.17.0
  scroll_edge_listener: ^0.1.1
  shared_preferences: ^2.0.15
  smooth_page_indicator: ^1.0.1
  dynamic_height_grid_view: ^0.0.3
  equatable: ^2.0.5
  floor: ^1.4.2
  package_info_plus: ^8.0.0
  flutter_native_splash: ^2.2.18
  dartz: ^0.10.1
  very_good_infinite_list: ^0.7.0
  uuid: ^4.4.2
  cached_network_image: ^3.2.3
  transparent_image: ^2.0.1
  flutter_dotenv: ^5.0.2

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^1.4.2
  build_runner: ^2.1.2

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
